# make nice fancy compositing
xcompmgr -c -f -F &

# make capslock an additional control key
setxkbmap -option ctrl:nocaps

# set the cursor speed to something reasonable
xset m 5 1

# enable xscreensaver
nohup xscreensaver -no-splash > /dev/null &

# use a real cursor
xsetroot -cursor_name left_ptr

# set a wallpaper
feh --bg-fill ~/.config/wallpaper

# Run ssh-agent for this session
eval $(ssh-agent)
